### PR TITLE
Do not fork all children at the same time

### PR DESCRIPTION
**Pull request by titas**
Reduce resouce pressure when spawning multiple childs

@laurynas, what do you think?

That would be first part of this: https://trello.com/c/GfUri8Fh/173-reduce-sidekiq-inactive-period-on-deploy-7-minutes-of-inactivity-during-deploy-restart

### CODE REVIEW

**Comment by laurynas** [comment]
Looks :ok: I would suggest having 1s or 0s as default.

**Comment by titas** [comment]
@laurynas, why 1 or 0?

**Comment by laurynas** [comment]
I think it is good default for small projects

**Comment by titas** [comment]
@laurynas - reduced to 1, bumped version

**Pull request merged**
